ScrumToPractice.Web/Areas/Administrativo/Controllers/QuestaoController.cs
using ScrumToPractice.Domain.Abstract;
using ScrumToPractice.Domain.Models;
using ScrumToPractice.Domain.Service;
using ScrumToPractice.Web.Areas.Administrativo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ScrumToPractice.Web.Areas.Administrativo.Controllers
{
    [Authorize]
    public class QuestaoController : Controller
    {
        private IBaseService<Questao> service;
        private ILogin login;

        public QuestaoController()
        {
            service = new QuestaoService();
            login = new UsuarioService();
        }

        // GET: Administrativo/Questao
        public ActionResult Index(int? idArea)
        {
            if (idArea == null)
            {
                idArea = 0;
            }

            var questoes = service.Listar()
                .Where(x => x.Ativo == true)
                .OrderBy(x => x.Descricao).ToList();

            ViewBag.IdArea = idArea;
            return View(new AreaQuestoes {
                Areas =  GetAreas(idArea), 
                Questoes = questoes });
        }

        private static List<SelectListItem> GetAreas(int? idArea)
        {
            IBaseService<Area> areaService = new AreaService();

            var areas = areaService.Listar().Where(x => x.Ativo == true)
                .OrderBy(x => x.Descricao).ToList();

            var areaItens = new List<SelectListItem>();
            foreach (var item in areas)
            {
                areaItens.Add(new SelectListItem { Text = item.Descricao, Value = item.Id.ToString(), Selected = (item.Id == idArea) });
            }
            return areaItens;
        }

        // GET: Administrativo/Questao/Details/5
        public ActionResult Details(int id, int idArea)
        {
            var questao = service.Find(id);

            if (questao == null)
            {
                return HttpNotFound();
            }

            ViewBag.IdArea = idArea;
            return View(questao);
        }

        // GET: Administrativo/Questao/Create
        public ActionResult Create(int ?idArea)
        {
            if (idArea == null)
            {
                idArea = 0;
            }

            AreaQuestao areaQuestao = GetNovaAreaQuestao(idArea);

            ViewBag.IdArea = idArea;
            return View(areaQuestao);
        }

        // POST: Administrativo/Questao/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Descricao,ComentarioScrum,MultiplaEscolha,Cortesia")] Questao questao, FormCollection collection)
        {
            try
            {
                questao.IdArea = int.Parse(Request.Form["Areas"]);
                questao.AlteradoEm = DateTime.Now;
                questao.Ativo = true;
                questao.AlteradoPor = login.GetIdUsuario(System.Web.HttpContext.Current.User.Identity.Name);
                TryUpdateModel(questao);

                if (ModelState.IsValid)
                {
                    // inclui a questao
                    questao.Id = service.Gravar(questao);                    

                    // rediciona para o cadastramento das respostas para esta questao
                    return RedirectToAction("Create", "Resposta", new { idQuestao = questao.Id });
                }
                var areaQuestao = GetNovaAreaQuestao(questao.IdArea);
                return View(areaQuestao);
            }
            catch (ArgumentException e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
                var areaQuestao = GetNovaAreaQuestao(int.Parse(Request.Form["Areas"]));
                return View(areaQuestao);
            }
        }

        // GET: Administrativo/Questao/Edit/5
        public ActionResult Edit(int? id, int? idArea)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var questao = service.Find((int)id);

            if (questao == null)
            {
                return HttpNotFound();
            }

            var areaQuestao = GetNovaAreaQuestao(questao.IdArea, questao);
            if (idArea == null)
            {
                idArea = 0;
            }
            ViewBag.IdArea = idArea;
            return View(areaQuestao);
        }

        // POST: Administrativo/Questao/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,Descricao,ComentarioScrum,MultiplaEscolha,Cortesia,Ativo")] Questao questao, FormCollection collection, int? idArea)
        {
            try
            {
                questao.AlteradoEm = DateTime.Now;
                questao.AlteradoPor = login.GetIdUsuario(System.Web.HttpContext.Current.User.Identity.Name);
                TryUpdateModel(questao);

                if (ModelState.IsValid)
                {
                    questao.IdArea = int.Parse(Request.Form["ddlArea"]);
                    service.Gravar(questao);
                    return RedirectToAction("Index");
                }
                var areaQuestao = GetNovaAreaQuestao(questao.IdArea, questao);
                if (idArea == null)
                {
                    idArea = 0;
                }
                ViewBag.IdArea = idArea;
                return View(areaQuestao);
            }
            catch (ArgumentException e)
            {
                var areaQuestao = GetNovaAreaQuestao(questao.IdArea, questao);
                if (idArea == null)
                {
                    idArea = 0;
                }
                ViewBag.IdArea = idArea;
                ModelState.AddModelError(string.Empty, e.Message);
                return View(areaQuestao);
            }
        }

        // GET: Administrativo/Questao/Delete/5
        public ActionResult Delete(int? id, int? idArea)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (idArea == null)
            {
                idArea = 0;
            }

            var questao = service.Find((int)id);

            if (questao == null)
            {
                return HttpNotFound();
            }

            ViewBag.IdArea = idArea;
            return View(questao);
        }

        // POST: Administrativo/Questao/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id, int? idArea)
        {
            try
            {
                service.Excluir(id);

                if (idArea == null)
                {
                    idArea = 0;
                }

                return RedirectToAction("Index", new { idArea = idArea });
            }
            catch
            {
                return View();
            }
        }

        // GET: Administrativo/Questao/Imprimir
        public ActionResult Imprimir(int? id)
        {
            if (id == null)
            {
                id = 0;
            }

            var questoes = service.Listar()
                .Where(x => x.Ativo == true && (id == 0 || x.IdArea == id))
                .ToList()
                .OrderBy(x => x.Area.Descricao)
                .ThenBy(x => x.Descricao)
                .AsEnumerable();

            if (id == 0 || questoes.Count() == 0)
            {
                ViewBag.Area = "";
            }
            else
            {
                ViewBag.Area = " - " + questoes.First().Area.Descricao;
            }

            return View(questoes);
        }


        #region [ Partial ]

        public PartialViewResult Questoes(int? idArea)
        {
            if (idArea == null)
            {
                idArea = 0;
            }

            var questoes = service.Listar().Where(x => (idArea == 0 || x.IdArea == idArea)).ToList();

            ViewBag.IdArea = idArea;
            return PartialView("_Questoes", questoes);
        }

        #endregion


        #region [ Methods ]

        private AreaQuestao GetNovaAreaQuestao(int? idArea, Questao questao = null)
        {
            if (questao == null)
            {
                questao = new Questao();
            }
            AreaQuestao areaQuestao = new AreaQuestao
            {
                Areas = GetAreas(idArea),
                Questao = questao
            };
            return areaQuestao;
        }

        #endregion

    }
}

ScrumToPractice.Web/Areas/Administrativo/Controllers/RespostaController.cs
using ScrumToPractice.Domain.Abstract;
using ScrumToPractice.Domain.Models;
using ScrumToPractice.Domain.Service;
using ScrumToPractice.Web.Areas.Administrativo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ScrumToPractice.Web.Areas.Administrativo.Controllers
{
    [Authorize]
    public class RespostaController : Controller
    {
        IBaseService<Resposta> service;
        ILogin login;

        public RespostaController()
        {
            service = new RespostaService();
            login = new UsuarioService();
        }

        // GET: Administrativo/Resposta
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // respostas desta questao
            var respostas = GetRespostas((int)id);
            var questaoRespostas = new QuestaoRespostas
            {
                Questao = new ScrumToPractice.Domain.Service.QuestaoService().Find((int)id),
                Respostas = GetRespostas((int)id)
            };

            return View(questaoRespostas);
        }

        // GET: Administrativo/Resposta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var resposta = service.Find((int)id);

            if (resposta == null)
            {
                return HttpNotFound();
            }

            return View(resposta);
        }

        // GET: Administrativo/Resposta/Create
        public ActionResult Create(int? idQuestao)
        {
            if (idQuestao == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var resposta = new Resposta { IdQuestao = (int)idQuestao };
            return View(resposta);
        }

        // POST: Administrativo/Resposta/Create
        [HttpPost]
        public ActionResult Create([Bind(Include="IdQuestao,Descricao,Correta")] Resposta resposta)
        {
            try
            {
                resposta.AlteradoEm = DateTime.Now;
                resposta.AlteradoPor = login.GetIdUsuario(System.Web.HttpContext.Current.User.Identity.Name);
                resposta.Ativo = true;
                TryUpdateModel(resposta);

                if (ModelState.IsValid)
                {
                    service.Gravar(resposta);
                    return RedirectToAction("Index", new { id = resposta.IdQuestao });
                }
                return View(resposta);
            }
            catch
            {
                return View(resposta);
            }
        }

        // GET: Administrativo/Resposta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var resposta = service.Find((int)id);
            if (resposta == null)
            {
                return HttpNotFound();
            }
            
            return View(resposta);
        }

        // POST: Administrativo/Resposta/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include="Id,IdQuestao,Descricao,Correta,Ativo")] Resposta resposta)
        {
            try
            {
                resposta.AlteradoEm = DateTime.Now;
                resposta.AlteradoPor = login.GetIdUsuario(System.Web.HttpContext.Current.User.Identity.Name);
                TryUpdateModel(resposta);

                if (ModelState.IsValid)
                {
                    service.Gravar(resposta);
                    return RedirectToAction("Index", new { id = resposta.IdQuestao });
                }
                return View(resposta);
            }
            catch
            {
                return View(resposta);
            }
        }

        // GET: Administrativo/Resposta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var resposta = service.Find((int)id);
            if (resposta == null)
            {
                return HttpNotFound();
            }
            return View(resposta);
        }

        // POST: Administrativo/Resposta/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, int? idQuestao)
        {
            try
            {
                if (id == null || idQuestao == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                service.Excluir((int)id);

                return RedirectToAction("Index", new { id = idQuestao });
            }
            catch
            {
                return View();
            }
        }

        private IEnumerable<Resposta> GetRespostas(int idQuestao)
        {
            var respostas = service.Listar().Where(x => x.IdQuestao == idQuestao).AsEnumerable();
            return respostas;
        }
    }
}

ScrumToPractice.Web/Areas/Administrativo/Views/Resposta/Create.cshtml
@model ScrumToPractice.Domain.Models.Resposta

@{
    ViewBag.Title = "Resposta - inclusão";
}

<div class="top50">
    <h3>Inclusão de resposta</h3>
    <strong>@Model.Questao.Descricao</strong>
</div>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal top50">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("IdQuestao", (int)Model.IdQuestao)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", @autofocus = true } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Correta)
                    @Html.ValidationMessageFor(model => model.Correta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Incluir" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", new { id = Model.IdQuestao })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumToPractice.Web/Areas/Administrativo/Views/Resposta/Delete.cshtml
@model ScrumToPractice.Domain.Models.Resposta

@{
    ViewBag.Title = "Resposta - excluir";
}

<div class="top50">
    <h3>Exclusao de resposta</h3>
    <strong>@Model.Questao.Descricao</strong>
</div>
<div class="text-danger top40">
    <h3>Confirma a exclusão desta resposta?</h3>
</div>
<div class="top50">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlteradoPor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlteradoPor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlteradoEm)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdQuestao)
        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index", new { id = Model.IdQuestao })
        </div>
    }
</div>

ScrumToPractice.Web/Areas/Administrativo/Views/Resposta/Details.cshtml
@model ScrumToPractice.Domain.Models.Resposta

@{
    ViewBag.Title = "Details";
}

<div class="top50">
    <strong>@Model.Questao.Descricao</strong>
</div>

<div>
    <h4>Resposta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlteradoPor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlteradoEm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlteradoEm)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index", new { id = Model.IdQuestao })
</p>

ScrumToPractice.Web/Areas/Administrativo/Views/Resposta/Edit.cshtml
@model ScrumToPractice.Domain.Models.Resposta

@{
    ViewBag.Title = "Resposta - alteração";
}

<div class="top50">
    <h3>Alteração de resposta</h3>
    <strong>@Model.Questao.Descricao</strong>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Resposta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdQuestao)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2", @autofocus = true })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Correta)
                    @Html.ValidationMessageFor(model => model.Correta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlteradoPor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Usuario.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlteradoEm, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.AlteradoEm, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", new { id = Model.IdQuestao })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumToPractice.Web/Areas/Administrativo/Views/Resposta/Index.cshtml
@model ScrumToPractice.Web.Areas.Administrativo.Models.QuestaoRespostas

@{
    ViewBag.Title = "Questões";
}

<div class="top50">
    <h3>@Model.Questao.Descricao</h3>
</div>

<p class="top20">
    @Html.ActionLink("Nova resposta", "Create", new { idQuestao = Model.Questao.Id })
</p>

<div class="container">
    <div class="row top10">
        <div id="respostas" class="col-sm-12">
            @{Html.RenderPartial("_Respostas", Model.Respostas);}
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Voltar", "Index", "Questao")
</p>