ScrumToPractice.Web/Areas/Practice/Controllers/PracticeController.cs
using ScrumToPractice.Domain.Abstract;
using ScrumToPractice.Domain.Models;
using ScrumToPractice.Domain.Service;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ScrumToPractice.Web.Areas.Practice.Controllers
{
    public class PracticeController : Controller
    {
        private ISimuladoCortesia cortesia;
        private IBaseService<CorSimulado> serviceSimulado;

        public PracticeController()
        {
            cortesia = new CortesiaSimulado();
            serviceSimulado = new CorSimuladoService();
        }

        // GET: Practice/Practice
        public ActionResult Index(int? idSimulado, QuestaoCortesia questaoCortesia)
        {
            if (questaoCortesia.NumQuestoesTotal > 0)
            {
                return View(questaoCortesia);
            }

            QuestaoCortesia questao;

            if (idSimulado == null)
            {
                // cria um novo simulado
                var simulado = cortesia.GetSimulado(cortesia.CriarSimulado());
                var alternativa = simulado.QuestoesSimuladas.ToList().OrderBy(x => x.Id).First();
                questao = cortesia.GetQuestao(alternativa.IdCortesia, alternativa.IdQuestao);
            }
            else
            {
                questao = cortesia.GetQuestao((int)idSimulado);
            }
           
            // retorna view com a primeira questao
            return View(questao);
        }
        
        /// <summary>
        /// Grava a resposta e retorna a proxima
        /// </summary>
        /// <param name="selecionadas"></param>
        /// <param name="idCortesia"></param>
        /// <param name="idQuestao"></param>
        /// <returns></returns>
        public ActionResult Proxima(IEnumerable<int> selecionadas, int idCortesia, int idQuestao)
        {
            // grava resposta usuario para a questao
            GravarResposta(idQuestao, selecionadas);            

            var proximaQuestao = cortesia.GetProximaQuestao(idCortesia, idQuestao);
            return PartialView("_QuestaoCortesia", (QuestaoCortesia)proximaQuestao);
        }

        /// <summary>
        /// Grava resposta e retorna a anterior
        /// </summary>
        /// <param name="selecionadas"></param>
        /// <param name="idCortesia"></param>
        /// <param name="idQuestao"></param>
        /// <returns></returns>
        public ActionResult Anterior(IEnumerable<int> selecionadas, int idCortesia, int idQuestao)
        {
            // grava resposta usuario para a questao
            GravarResposta(idQuestao, selecionadas);

            var questaoAnterior = cortesia.GetQuestaoAnterior(idCortesia, idQuestao);
            return PartialView("_QuestaoCortesia", (QuestaoCortesia)questaoAnterior);
        }

        /// <summary>
        /// Define que esta questao sera respondida depois
        /// </summary>
        /// <param name="idCortesia"></param>
        /// <param name="idQuestao"></param>
        /// <returns>Proxima questao a ser respondida, se nao houver retorna a anterior</returns>
        public ActionResult ResponderDepois(int idCortesia, int idQuestao)
        {
            var questao = cortesia.ResponderDepois(idCortesia, idQuestao);
            return PartialView("_QuestaoCortesia", (QuestaoCortesia)questao);
        }

        /// <summary>
        /// Exibe uma determinada questao
        /// </summary>
        /// <param name="idQuestao"></param>
        /// <returns></returns>
        public ActionResult ExibirQuestao(IEnumerable<int> selecionadas, int idCortesia, int idQuestao, int idQuestaoAtual)
        {
            // grava resposta usuario para a questao
            GravarResposta(idQuestaoAtual, selecionadas);

            var questao = cortesia.GetQuestao(idCortesia, idQuestao);
            return PartialView("_QuestaoCortesia", (QuestaoCortesia)questao);
        }

        /// <summary>
        /// Grava a ultima resposta e redireciona para o controller do resultado
        /// </summary>
        /// <param name="selecionadas"></param>
        /// <param name="idCortesia"></param>
        /// <param name="idQuestao"></param>
        /// <returns></returns>
        public ActionResult Finish(IEnumerable<int> selecionadas, int idCortesia, int idQuestao)
        {
            // grava resposta usuario para a questao
            GravarResposta(idQuestao, selecionadas);

            // redireciona para o controller do resultado
            return Json(new { result = "Redirect", url = Url.Action("Index", "Result", new { idCortesia = idCortesia }) });
        }

        /// <summary>
        /// Grava resposta conforme selecao do usuario
        /// </summary>
        /// <param name="idQuestao"></param>
        /// <param name="selecionadas"></param>
        private void GravarResposta(int idQuestao, IEnumerable<int> selecionadas)
        {
            cortesia.GravarRespostaUsuario(idQuestao, selecionadas);
        }
    }
}

ScrumToPractice.Web/Controllers/GuideController.cs
using System.Web.Mvc;

namespace ScrumToPractice.Web.Controllers
{
    public class GuideController : Controller
    {
        // GET: Guide
        public ActionResult Index()
        {
            return View();
        }

        // GET: Guide/Read
        public ActionResult Read()
        {
            return View();
        }
    }
}

ScrumToPractice.Web/Areas/Practice/Views/Shared/_Correcao.cshtml
@model IEnumerable<ScrumToPractice.Domain.Models.QuestaoCorrigida>

<h3 class="text-danger">Incorrect Answers:</h3>

@foreach (var questao in Model.Where(x => x.Questao.Correto == false))
{
    <hr class="top40" />
    <h4>@questao.Questao.Questao.Descricao</h4>
    <small>(@questao.Questao.Area.Descricao)</small>

    <div class="table-responsive top10">
        <table class="table-responsive">
            <thead>
                <tr class="active">
                    <th>Your Answer</th>
                    <th class="pleft20">Correct Answer</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="w50 top">
                        @if (questao.SelecaoAluno.Count() > 0)
                        {
                            foreach (var respostaAluno in questao.SelecaoAluno)
                            {
                                @respostaAluno.Resposta.Descricao
                                <br />
                            }
                        }
                        else
                        {
                            @:You do not answered this question
                        }
                    </td>
                    <td class="w50 pleft20 top">
                        @foreach (var respostaSistema in questao.SelecaoSistema)
                        {
                            @respostaSistema.Resposta.Descricao
                            <br />
                        }
                    </td>
                </tr>
            </tbody>
        </table>
    </div>    
}
<div class="container top40">
    <div class="row text-center">
        <div class="col-xs-12 col-md-12">
            @Html.ActionLink("Try again", "Index", "Practice", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

ScrumToPractice.Web/Areas/Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Scrum, Scrum Practice Exam, Scrum Certification, Scrum Test Questions, Simulado Scrum" />
    <meta name="description" content="Scrum Practice Exam" />
    <title>@ViewBag.Title - ScrumToPractice.com</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" rel="home" href="/Home" title="ScrumToPractice">
                    <img style="max-width:100px; margin-top: -7px; height:80px; width:80px;" src="~/Images/logo_top_menu.gif">
                </a>
            </div>
            @using (@Html.BeginForm("PostToPaypal", "Home", new { area = "" }, FormMethod.Post, new { @id = "frmPostToPayPal" }))
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Courtesy", "Index", "Practice", new { area = "" }, null)</li>
                        <li><a href="#" id="fullAccess">Full access</a></li>
                        <li>@Html.ActionLink("Resources", "Index", "Guide", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                    </ul>
                </div>
            }
        </div>
    </div>

    <div class="container body-content top40">
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; @DateTime.Now.Year - ScrumToPractice.com<br />
                <small class="gray">The logos and names of third-party is copyrighted or their respective owners</small>
            </p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script src="~/Scripts/bootstrap.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {

            $('#fullAccess').click(function () {
                $('form#frmPostToPayPal').submit();
            });

        });
    </script>
</body>
</html>

ScrumToPractice.Web/Areas/Practice/Views/Shared/_QuestaoCortesia.cshtml
@using ScrumToPractice.Domain.Models;
@model  QuestaoCortesia

@Html.Hidden("idCortesia", (int)@Model.QuestaoUsuario.IdCortesia)
@Html.Hidden("idQuestao", (int)@Model.QuestaoUsuario.Id)

<div id="simulado">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h4>
                    @Model.NumQuestaoAtual - @Model.QuestaoUsuario.Questao.Descricao
                </h4>
            </div>
        </div>

        <div class="row top20">
            <div class="col-sm-12 col-md-12">

                @if (@Model.QuestaoUsuario.Questao.MultiplaEscolha)
                {
                    @:(Multiple-choice)
                    @Html.Partial("_QuestaoUsuarioEscolhaMultipla", (IEnumerable<ScrumToPractice.Domain.Models.CorResposta>)@Model.QuestaoUsuario.RespostasUsuario)
                }
                else
                {
                    @:(Select one)
                    @Html.Partial("_QuestaoUsuarioEscolhaSimples", (IEnumerable<ScrumToPractice.Domain.Models.CorResposta>)@Model.QuestaoUsuario.RespostasUsuario)
                }
                <hr />
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            @Html.Hidden("idCortesia", (int)Model.QuestaoUsuario.IdCortesia)
            <div class="col-xs-4 col-sm-4 col-md-4">
                <input id="btnPrevious" type="button" value="Previous" data-questao="@Model.QuestaoUsuario.Id" style='@(Model.PrimeiraQuestao ? "visibility:hidden" : "visibility:visible")' class="btn btn-primary" />
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8 text-right">
                <input id="btnAnswerLater" type="button" value="Answer later" data-questao="@Model.QuestaoUsuario.Id" class="btn btn-primary" style='@(Model.UltimaQuestao ? "visibility:hidden" : "visibility:visible")' />
                <input id="btnNext" type="button" value="Next" data-questao="@Model.QuestaoUsuario.Id" class="btn btn-primary" style='@(Model.UltimaQuestao ? "visibility:hidden" : "visibility:visible")' />
                <input id="btnFinish" type="button" value="Finish exam" data-questao="@Model.QuestaoUsuario.Id" class="btn btn-primary" style='@(Model.Concluir ? "visibility:visible" : "visibility:hidden")' />
            </div>
        </div>
    </div>
</div>

@if (@Model.QuestoesNaoRespondidas.Count() > 0)
{
    <hr />
    <div class="container">
        <div class="row">
            <h4>Marked for answer later</h4>
            <div class="col-sm-12 col-md-12">
                @foreach (CorSimulado item in Model.QuestoesNaoRespondidas)
                {
                    <p><button type="button" data-questao="@item.IdQuestao" class="btn btn-primary btn-xs answer">Answer</button> @item.Questao.Descricao</p>
                }
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Areas/Practice/Scripts/QuestaoCortesia.js"></script>

ScrumToPractice.Web/Areas/Practice/Views/Shared/_QuestaoUsuarioEscolhaMultipla.cshtml
@model IEnumerable<ScrumToPractice.Domain.Models.CorResposta>

<hr />
@foreach (ScrumToPractice.Domain.Models.CorResposta item in @Model)
{
    <p>@Html.CheckBox("alternativa", item.SelecaoUsuario, new { id = "Alternativa", @class = "alternativa", value=@item.Id }) @item.Resposta.Descricao</p>
}

ScrumToPractice.Web/Areas/Practice/Views/Shared/_QuestaoUsuarioEscolhaSimples.cshtml
@model IEnumerable<ScrumToPractice.Domain.Models.CorResposta>

<hr />
@foreach (ScrumToPractice.Domain.Models.CorResposta item in @Model)
{
    <p>@Html.RadioButton("alternativa", item.Id, item.SelecaoUsuario, new { id = "Alternativa", @class = "alternativa" }) @item.Resposta.Descricao</p>
}